# config/packages/calliostro_spotify_web_api.yaml
calliostro_spotify_web_api:

  # Your Client ID
  client_id:            'e04ac8e95b394c4389761e90a8135199' # Required

  # Your Client Secret
  client_secret:        '5d3fcc5c2fde4501a548561eb0287246' # Required

  # Options for SpotifyWebAPI client
  # https://github.com/jwilsson/spotify-web-api-php/blob/main/docs/examples/setting-options.md
  options:
    auto_refresh:         false
    auto_retry:           false
    return_assoc:         false

  # Address to redirect to after authentication success OR failure
  redirect_uri:         'https://127.0.0.1:8000/callback/' # Example: 'https://127.0.0.1:8000/callback/'

  # Service ID of the token provider that provides the user's access token
  #token_provider:       calliostro_spotify_web_api.token_provide